title: Ruang Belajar - Java
description: Repositori pembelajaran mata kuliah pemrograman Java
domain: pujangga123.github.io
url: http://pujangga123.github.io
github_username:  pujangga123

remote_theme: pages-themes/minimal
plugins:
- jekyll-remote-theme
- jekyll-feed1